### ISSUE TITLE
Support sample_weight

### ISSUE THREAD

**Issue by lizeyan** [d-chambers/dbscan1d#11]
> sample_weight
array-like of shape (n_samples,), default=None
Weight of each sample, such that a sample with a weight of at least min_samples is by itself a core sample; a sample with a negative weight may inhibit its eps-neighbor from being core. Note that weights are absolute, and default to 1.

https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html

**Comment by d-chambers** [comment]
closed by #12
