### ISSUE TITLE
Inconsistent labels values when there is only one cluster

### ISSUE THREAD

**Issue by Mpal7** [d-chambers/dbscan1d#3]
First and foremost thank you for this efficient implementation of the alghoritm for 1D data.  
With that being said i noticed that the labelling seems to be inconsistent, when there is only one cluster sometimes the points belonging to the cluster are labeled with 1 sometimes with 0, why does this happen and could it happen when there's more than one cluster? 
Following a reproducibile example:
label_is_zero=[86400.0,86400.0,86400.0,86401.0,86399.0,86400.0,86401.0,86399.0,86400.0,86400.0,86400.0,86402.0,86398.0,86401.0,86399.0,86401.0,86400.0,86399.0,86399.0,86401.0,86399.0,86401.0,86399.0,86402.0,86399.0,86400.0,86401.0,86401.0]
label_is_one=[46823, 46818, 46816, 46816, 46819]

**Comment by d-chambers** [comment]
label_is_one doesn't cluster with the default params. What values for `eps` and `min_samples` are you using?

**Comment by Mpal7** [comment]
Sorry, completely forgot values are `eps=5`, `min_samples = 3`

**Comment by d-chambers** [comment]
Thanks @Mpal7, fixed in #5.
