### ISSUE TITLE
dbscan metric

### ISSUE THREAD

**Issue by priamai** [d-chambers/dbscan1d#6]
Hi there,
I noticed that the metric is not included in the constructor which will make it incompatible with DBSCAN official version should support:

`dbs = DBSCAN1D(eps=1.0, min_samples=10,metric='Euclidean')`

I have looked into the code and I can see from here:

```
    def _get_is_core(self, ar):
        """ Determine if each point is a core. """
        mineps = np.searchsorted(ar, ar - self.eps, side="left")
        maxeps = np.searchsorted(ar, ar + self.eps, side="right")
        core = (maxeps - mineps) >= self.min_samples
        return core
```

That is equivalent to euclidean distance in one dimension abs(p1-p2), is this correct?
Would there be any point in supporting other distances in 1 dimension which are not many but for example will be useful to have (p1-p2)^2.

Maybe throw an exception for any other non supported distances?

**Comment by d-chambers** [comment]
Hi,

Thanks for filling the issue. After thinking about this some, I don't think it makes sense in 1D to specify a metric. For each metric, one of two things will happen:

1) The metrics converge and, if not equal, produce the ordering of points 

For example, Euclidean (L2) and Manhattan (L1) distance are identical in 1D. The squared distance you mentioned (note it needs a sqrt to be Euclidean) would not preserve the distance between each point but would preserve the ordering of the 1D array and thus the clustering (provided eps is adjusted accordingly)

2) The metric is meaningless in 1D

For example, cosine distance will produce a distance of 1 between each pair (not helpful)

I guess we can just include the keyword and through an error if it is not in 'Euclidean', 'L2', 'L1', or 'Manhattan' which are all the same in 1D.

**Comment by priamai** [comment]
Yes, you refreshed my vector space algebra which is 20 years old ah!
I totally agree on your suggestion.
Cheers.
